application: yogelise
version: 1
api_version: 1
runtime: python27
threadsafe: no

handlers:
  
  - url: /css
    static_dir: resources/css
    
  - url: /img
    static_dir: resources/img
    
  - url: /js
    static_dir: resources/js

  - url: /.*
    script: main.py

##all above is stock